---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ffw
  name: ffw
data:
  default.conf.template: |
      server {
          listen       8080;
          server_name  localhost;
          location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
          }
          #error_page  404              /404.html;
          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
              root   /usr/share/nginx/html;
          }
          #location ~ \.php$ {
          #    root           html;
          #    fastcgi_pass   127.0.0.1:9000;
          #    fastcgi_index  index.php;
          #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
          #    include        fastcgi_params;
          #}
          add_header 'Access-Control-Allow-Origin' '$CORS_ORIGN';
          add_header 'Access-Control-Allow-Methods' '$CORS_METHODS';
      }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ffw
  name: ffw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ffw
  template:
    metadata:
      labels:
        app: ffw
    spec:
      containers:
      - image: docker.io/nginxinc/nginx-unprivileged:1.27.1-alpine-slim
        name: nginx-unpriviledged
        env:
        - name: CORS_ORIGN
          value: '*'
        - name: CORS_METHODS
          value: 'GET,PUT,POST,OPTIONS'
        ports:
        - containerPort: 8080
          hostPort: 3000
          name: http
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: config
          mountPath: "/etc/nginx/templates"
          readOnly: true
        - name: data
          mountPath: "/usr/share/nginx/html"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: ffw
          items:
          - key: "default.conf.template"
            path: "default.conf.template"
      - name: data
        hostPath:
          path: "/home/nicolas/git/apps/woob-ffIII/frontend/dist"
          type: Directory
