---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ffw
  name: ffw
data:
  ADDHEADER: |
    :
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET,PUT,POST,OPTIONS';
    add_header 'Content-Security-Policy' 'default-src 'self';connect-src 'self' firefly.local;';
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ffw
  name: ffw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ffw
  template:
    metadata:
      labels:
        app: ffw
    spec:
      containers:
      - image: docker.io/nginxinc/nginx-unprivileged:1.27.1-alpine-slim
        name: frontend
        env:
        - name: APIURL
          value: http://unix:/var/run/python/api.sock
        - name: ADDHEADER
          value: |
            :
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET,PUT,POST,OPTIONS';
            add_header 'Content-Security-Policy' 'default-src 'self';connect-src 'self' firefly.local;';
        ports:
        - containerPort: 8080
          hostPort: 3000
          name: http
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: socket
          mountPath: "/var/run/python"
          readOnly: true
      - image: wff-api:latest
        name: api
        workingDir: /app
        command:
        - uvicorn
        args:
        - app:app
        - --uds
        - /var/run/python/api.sock
        - --workers
        - 3
        - --reload
        env:
        - name: PYTHONPYCACHEPREFIX
          value: /tmp/pycache
        - name: PS1
          value: '(venv) \w \$ '
        resources: {}
        volumeMounts:
        - name: socket
          mountPath: "/var/run/python"
        - name: cache
          mountPath: "/tmp/pycache"
        - name: venv
          mountPath: "/venv"
          readOnly: true
        - name: api
          mountPath: "/app"
          readOnly: true
      hostAliases:
      - hostnames:
        - firefly.local
        ip: '192.168.1.161'
      volumes:
      - name: config
        configMap:
          name: ffw
          items:
          - key: "default.conf.template"
            path: "default.conf.template"
      - name: frontend
        hostPath:
          path: "/home/nicolas/git/apps/woob-ffIII/frontend/dist"
          type: Directory
      - name: api
        hostPath:
          path: "/home/nicolas/git/apps/woob-ffIII/backend/src/app"
          type: Directory
      - name: socket
        emptyDir:
          medium: Memory
          sizeLimit: 10Mi
      - name: venv
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
      - name: cache
        emptyDir:
          medium: Memory
          sizeLimit: 200Mi